# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets ,QDialog
from PyQt5.QtWidgets import QMessageBox


class infobox:
    type_array = [QMessageBox.Information,QMessageBox.Question, QMessageBox.Warning,QMessageBox.critical]
    
    button_dic = {
        "ok": 0x00000400,
        "open": 0x00002000,
        "Save": 0x00000800,
        "Cancel": 0x00400000,
        "Close": 0x00200000,
        "Yes": 0x00004000,
        "No": 0x00010000,
        "Abort": 0x00040000,
        "Retry": 0x00080000,
        "Ignore": 0x00100000
    }
    
    def __init__(self,title,message,type,button ,func):
        self.title = title
        self.message = message
        self.type = self.typr_array[type]
        self.button = button
        self.func = func

    def showdialog(self):
        msg = QtCore.QMessageBox()
        msg.setIcon(self.type)

        msg.setText(self.title)
        msg.setInformativeText(self.message)
        # msg.setWindowTitle()
        # msg.setDetailedText()
        msg.setStandardButtons(self.button)
        msg.buttonClicked.connect(self.func)
            
        self.retval = msg.exec_()
        return self.retval
        #print ("value of pressed message box button:", retval)

    def funci(self):
        pass
