# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from Crypt.secret import *

class CustomDialog(QDialog):
    def __init__(self,ts ,to ,from_,subject,contents,caller ,parent=None):
        super().__init__(parent)
        self.ref = caller.ref
        if to.endswith("(YOU)") :
            self.me = to[:-5]
            self.you = from_
            
        else :
            self.me = from_[:-5]
            self.you = to

        self.setWindowTitle("dialog")
        self.resize(500, 500)
        #self.setObjectName("Dialog")
        self.ts=ts

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox()
        self.groupBox_2.setObjectName("groupBox_2")

        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.data_timestamp_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.data_timestamp_2.setFont(font)
        self.data_timestamp_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.data_timestamp_2.setObjectName("data_timestamp_2")
        self.gridLayout_2.addWidget(self.data_timestamp_2, 2, 2, 1, 1)
        self.data_sender_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.data_sender_2.setFont(font)
        self.data_sender_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.data_sender_2.setObjectName("data_sender_2")
        self.gridLayout_2.addWidget(self.data_sender_2, 0, 2, 1, 1)
        self.Reciver_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reciver_2.sizePolicy().hasHeightForWidth())
        self.Reciver_2.setSizePolicy(sizePolicy)
        self.Reciver_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Reciver_2.setObjectName("Reciver_2")
        self.gridLayout_2.addWidget(self.Reciver_2, 1, 0, 1, 1)
        self.data_reciver_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.data_reciver_2.setFont(font)
        self.data_reciver_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.data_reciver_2.setObjectName("data_reciver_2")
        self.gridLayout_2.addWidget(self.data_reciver_2, 1, 2, 1, 1)
        self.Sender_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sender_2.sizePolicy().hasHeightForWidth())
        self.Sender_2.setSizePolicy(sizePolicy)
        self.Sender_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Sender_2.setObjectName("Sender_2")
        self.gridLayout_2.addWidget(self.Sender_2, 0, 0, 1, 1)
        self.timestamp_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timestamp_2.sizePolicy().hasHeightForWidth())
        self.timestamp_2.setSizePolicy(sizePolicy)
        self.timestamp_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timestamp_2.setObjectName("timestamp_2")
        self.gridLayout_2.addWidget(self.timestamp_2, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox()
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.subject_data_2 = QtWidgets.QLabel(self.groupBox)
        self.subject_data_2.setFrameShape(QtWidgets.QFrame.Box)
        self.subject_data_2.setWordWrap(True)
        self.subject_data_2.setObjectName("subject_data_2")
        self.verticalLayout_3.addWidget(self.subject_data_2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 456, 210))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.content_data_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.content_data_2.setReadOnly(True)
        # self.content_data_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content_data_2.sizePolicy().hasHeightForWidth())
        self.content_data_2.setSizePolicy(sizePolicy)
        self.content_data_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_data_2.setText("")
        self.content_data_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        #self.content_data_2.setWordWrap(True)
        self.content_data_2.setObjectName("content_data_2")
        self.horizontalLayout_2.addWidget(self.content_data_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.pushButton = QtWidgets.QPushButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton.clicked.connect(self.decrypt)
        self.retranslateUi(ts ,to ,from_,subject,contents)

        # message = QLabel("Something happened, is that OK?")
        # self.layout.addWidget(message)
        # self.layout.addWidget(self.buttonBox)
        self.setLayout(self.verticalLayout)
        self.contents = contents


    def retranslateUi(self,ts ,to ,from_,subject,contents):
        self.groupBox_2.setTitle("Mail info :")
        self.data_timestamp_2.setText(ts)
        self.data_sender_2.setText(from_)
        self.Reciver_2.setText("Reciver    :    ")
        self.data_reciver_2.setText(to)
        self.Sender_2.setText("Sender    :    ")
        self.timestamp_2.setText("Time     :    ")
        self.groupBox.setTitle("Mail Contents :")
        self.label_5.setText("Subject :")
        self.subject_data_2.setText(subject)
        self.label_6.setText("Body :")
        self.pushButton.setText("Decrypt")
        self.content_data_2.setText(contents)
    
    def decrypt(self) :
        self.groupBox.setTitle("Mail Contents Decrypted :")
        secret = generate_secret(get_pub_key(self.you,self.ref),self.me)
        dec_content = decrypt(secret,self.contents)
        self.content_data_2.setText(dec_content)
        self.pushButton.setText("OK")
        self.pushButton.clicked.connect(self.close)
    
    def close(self):
        self.done(1)
        
        
