# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Chooser(object):
    def setupUi(self, MainWindow , login_info=None,ref=None):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 605)
        self.clicked=0
        self.Main_Window = QtWidgets.QWidget(MainWindow)
        self.Main_Window.setObjectName("Main_Window")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Main_Window)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Welcome = QtWidgets.QGridLayout()
        self.Welcome.setObjectName("Welcome")
        self.sign_up = QtWidgets.QPushButton(self.Main_Window)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.sign_up.setFont(font)
        self.sign_up.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 50, 255), stop:1 rgba(28, 113, 216, 255));\n"
"QPushButton { height: 100%; }; \n"
"Text-align: middle")
        self.sign_up.setSizePolicy ( QtWidgets.QSizePolicy.Expanding , QtWidgets.QSizePolicy.Expanding )
        self.sign_up.setObjectName("sign_up")
        self.sign_up.clicked.connect(self.signup_click)
        

        self.login = QtWidgets.QPushButton(self.Main_Window)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.login.setFont(font)
        self.login.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 50, 255), stop:1 rgba(28, 113, 216, 255));\n"
"QPushButton { height: 100%; }; \n"
"Text-align: middle")
        self.login.setSizePolicy ( QtWidgets.QSizePolicy.Expanding , QtWidgets.QSizePolicy.Expanding )
        self.login.setObjectName("Login")
        self.login.clicked.connect(self.login_click)
        #self.login.linkActivated.connect(self.dosomestuff)
        self.Welcome.addWidget(self.login, 0, 0, 1, 1)
        self.Welcome.addWidget(self.sign_up, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.Welcome, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.Main_Window)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Signup or login"))
        self.sign_up.setText(_translate("MainWindow", "Sign Up"))
        self.login.setText(_translate("MainWindow", "login"))





    def signup_click(self):
        self.clicked=1
        self.next=2
        QtWidgets.qApp.quit()
    
    def login_click(self):
        self.clicked=1
        self.next=3
        QtWidgets.qApp.quit()

    

