# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import UI
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow ,login_info=None,ref=None):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 605)
        self.clicked=0
        self.Main_Window = QtWidgets.QWidget(MainWindow)
        self.Main_Window.setObjectName("Main_Window")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Main_Window)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Welcome = QtWidgets.QGridLayout()
        self.Welcome.setObjectName("Welcome")
        self.label = QtWidgets.QPushButton(self.Main_Window)
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 50, 255), stop:1 rgba(28, 113, 216, 255));\n"
"QPushButton { height: 100%; }; \n"
"Text-align: right" )
        self.label.setSizePolicy ( QtWidgets.QSizePolicy.Expanding , QtWidgets.QSizePolicy.Expanding )
        self.label.setObjectName("label")
        self.label.clicked.connect(self.click)
        #self.label.linkActivated.connect(self.dosomestuff)
        self.Welcome.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.Welcome, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.Main_Window)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Welcome to Secure Mails"))
        self.label.setText(_translate("MainWindow", "Welcome"))
    
    def click(self):
        self.clicked=1
        self.next=1
        QtWidgets.qApp.quit()
        

