# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editor_window(object):
    def setupUi(self, editor_window):
        editor_window.setObjectName("editor_window")
        editor_window.resize(761, 630)
        self.user_fulltabs = QtWidgets.QWidget(editor_window)
        self.user_fulltabs.setObjectName("user_fulltabs")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.user_fulltabs)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.user_tab = QtWidgets.QTabWidget(self.user_fulltabs)
        self.user_tab.setUsesScrollButtons(True)
        self.user_tab.setTabBarAutoHide(False)
        self.user_tab.setObjectName("user_tab")
        self.Inbox = QtWidgets.QWidget()
        self.Inbox.setObjectName("Inbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Inbox)
        self.gridLayout_3.setContentsMargins(0, 0, -1, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Inbox_grp = QtWidgets.QGroupBox(self.Inbox)
        self.Inbox_grp.setTitle("")
        self.Inbox_grp.setObjectName("Inbox_grp")
        self.gridLayout_3.addWidget(self.Inbox_grp, 0, 0, 1, 1)
        self.user_tab.addTab(self.Inbox, "")
        self.Sent = QtWidgets.QWidget()
        self.Sent.setObjectName("Sent")
        self.gridLayout = QtWidgets.QGridLayout(self.Sent)
        self.gridLayout.setContentsMargins(0, 0, -1, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.Sent_grp = QtWidgets.QGroupBox(self.Sent)
        self.Sent_grp.setTitle("")
        self.Sent_grp.setObjectName("Sent_grp")
        self.gridLayout.addWidget(self.Sent_grp, 0, 0, 1, 1)
        self.user_tab.addTab(self.Sent, "")
        self.Editor = QtWidgets.QWidget()
        self.Editor.setObjectName("Editor")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Editor)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.editor_grp = QtWidgets.QGroupBox(self.Editor)
        self.editor_grp.setTitle("")
        self.editor_grp.setObjectName("editor_grp")
        self.mail_sub = QtWidgets.QPlainTextEdit(self.editor_grp)
        self.mail_sub.setGeometry(QtCore.QRect(60, 170, 671, 91))
        self.mail_sub.setObjectName("mail_sub")
        self.mail_contents = QtWidgets.QTextEdit(self.editor_grp)
        self.mail_contents.setGeometry(QtCore.QRect(60, 290, 671, 201))
        self.mail_contents.setObjectName("mail_contents")
        self.label_9 = QtWidgets.QLabel(self.editor_grp)
        self.label_9.setGeometry(QtCore.QRect(130, 100, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.editor_grp)
        self.label_10.setGeometry(QtCore.QRect(70, 140, 657, 18))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.editor_grp)
        self.label_11.setGeometry(QtCore.QRect(70, 270, 657, 18))
        self.label_11.setObjectName("label_11")
        self.recever_email = QtWidgets.QLineEdit(self.editor_grp)
        self.recever_email.setGeometry(QtCore.QRect(180, 90, 471, 36))
        self.recever_email.setObjectName("recever_email")
        self.send_mail = QtWidgets.QPushButton(self.editor_grp)
        self.send_mail.setGeometry(QtCore.QRect(340, 510, 101, 41))
        self.send_mail.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(26, 95, 180);\n"
"background-color: rgb(53, 132, 228);\n"
"selection-background-color: rgb(26, 95, 180);")
        self.send_mail.setObjectName("send_mail")
        self.label = QtWidgets.QLabel(self.editor_grp)
        self.label.setGeometry(QtCore.QRect(320, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.editor_grp, 0, 0, 1, 1)
        self.user_tab.addTab(self.Editor, "")
        self.gridLayout_4.addWidget(self.user_tab, 0, 0, 1, 1)
        editor_window.setCentralWidget(self.user_fulltabs)

        self.retranslateUi(editor_window)
        self.user_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(editor_window)

    def retranslateUi(self, editor_window):
        _translate = QtCore.QCoreApplication.translate
        editor_window.setWindowTitle(_translate("editor_window", "MainWindow"))
        self.user_tab.setTabText(self.user_tab.indexOf(self.Inbox), _translate("editor_window", "Inbox"))
        self.user_tab.setTabText(self.user_tab.indexOf(self.Sent), _translate("editor_window", "Outbox"))
        self.label_9.setText(_translate("editor_window", "To"))
        self.label_10.setText(_translate("editor_window", "Subject:"))
        self.label_11.setText(_translate("editor_window", "Content:"))
        self.send_mail.setText(_translate("editor_window", "Send"))
        self.label.setText(_translate("editor_window", "EDITOR"))
        self.user_tab.setTabText(self.user_tab.indexOf(self.Editor), _translate("editor_window", "Editor"))
